### PR TITLE
[WIP] - Add documentation for token system

### PR DESCRIPTION
**Pull request by stefannibrasil**
After reading some API docs, I started writing the following one for the token system. But I have some questions:

- Which URL to send POST action?
- How does the user generate the token?

I am using Postman and I wasn't really sure about how to test it here using it.

### CODE REVIEW

**Comment by sukhbir-singh** [comment]
I wanted to contribute, so that i will try to send pull request to your branch `add-token-documentation`. Once this task is completed, we can make pull request from this branch to main plots2 repo with our combined work. :smile: @stefannibrasil It is cool for you??

**Comment by stefannibrasil** [comment]
@sukhbir-singh Yes, sure! Thanks for reaching out.

If you have something to add, feel free to go ahead and then we add our contributions using one branch. And if you have more questions to add to the list too, go ahead :)

**Comment by sukhbir-singh** [comment]
Route for comment :--
`post '/comment/create/token/id.:format', to: 'comment#create_by_token'`

then, url will be `localhost:3000/comment/create/token/55`

**Comment by sukhbir-singh** [comment]
@stefannibrasil I have added some more details about comment api in readme file please check it out. 

Answer to your question:-
* Access token for each user is being generated in `user` model class (method name is `set_token`) and is being stored in `rusers` table (in `access_token` column) in the database.

I have also uploaded a video regarding this token based based comment api to show how to make this post request with proper parameters and headers via postman. 

Youtube Link: https://youtu.be/scGHqk9csMQ

I hope this will help :smile:

**Comment by stefannibrasil** [comment]
Thanks, @sukhbir-singh for your help! I was too lost with all the files and I was trying to use Postman but didn't know exactly which URL to use... good work! :)

I'll open the PR and ping you there.

**Comment by sukhbir-singh** [comment]
Awesome!! :smile:

**Pull request merged**
